/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    carts: Cart;
    orders: Order;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'store-management': StoreManagement;
    'store-identity': StoreIdentity;
    'store-contact': StoreContact;
  };
  globalsSelect: {
    'store-management': StoreManagementSelect<false> | StoreManagementSelect<true>;
    'store-identity': StoreIdentitySelect<false> | StoreIdentitySelect<true>;
    'store-contact': StoreContactSelect<false> | StoreContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  phone?: string | null;
  address?: string | null;
  city?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  /**
   * URL directa en CDN de Cloudinary
   */
  cloudinaryURL?: string | null;
  cloudinaryPublicId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Organiza las categorías de productos de la tienda.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Nombre visible de la categoría en la tienda.
   */
  title: string;
  /**
   * Identificador para la URL (ej. ropa-de-verano). En minúsculas y separado por guiones.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gestión completa del catálogo de productos (sin barra lateral dividida).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  /**
   * Nombre claro y atractivo que verán los clientes en la tienda.
   */
  title: string;
  /**
   * Determina si el producto se muestra públicamente.
   */
  status: 'draft' | 'published';
  /**
   * Selecciona una o más categorías para organizar el producto.
   */
  category: (string | Category)[];
  /**
   * Detalla características y beneficios. Puedes usar subtítulos, negritas y listas.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Precio final que se cobrará al cliente en la tienda.
   */
  price: number;
  /**
   * Si es mayor al Precio Actual, aparecerá tachado indicando descuento.
   */
  compareAtPrice?: number | null;
  /**
   * Código único para identificación en tu inventario.
   */
  sku?: string | null;
  /**
   * Cantidad física disponible para la venta inmediata.
   */
  inventory: number;
  /**
   * Sube imágenes claras (recomendado formato 1:1 o cuadrado). La primera imagen será la portada.
   */
  media: (string | Media)[];
  /**
   * Agrega pares de datos técnicos (Ejemplo: Material -> Acero Inoxidable, Color -> Negro Mate).
   */
  specifications?:
    | {
        name: string;
        value: string;
        icon?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Identificador para la URL de la tienda (ejemplo: smartpulse-x7-wearable). En minúsculas y separado por guiones.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  lines?:
    | {
        merchandiseId: string;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pedidos guardados o realizados por clientes. Puedes consultar el teléfono y datos de envío para contactar por WhatsApp o procesar la orden.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  orderNumber: string;
  user?: (string | null) | User;
  status: 'saved' | 'whatsapp_sent' | 'processing' | 'completed' | 'cancelled';
  customer: {
    firstName: string;
    lastName: string;
    phone: string;
    address: string;
    city: string;
  };
  lines?:
    | {
        productName: string;
        quantity: number;
        price: number;
        merchandiseId?: string | null;
        id?: string | null;
      }[]
    | null;
  totalPrice: number;
  currency?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Páginas informativas de la tienda (ej: Preguntas Frecuentes, Envío, Devoluciones, Contacto).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Nombre de la página visible para los usuarios.
   */
  title: string;
  /**
   * Identificador URL (ej. faq, envio, contacto, devoluciones).
   */
  slug: string;
  status?: ('published' | 'draft') | null;
  /**
   * Si está activo, aparecerá un enlace a esta página en el pie de página.
   */
  showInFooter?: boolean | null;
  /**
   * Escribe y da formato al contenido de la página (títulos, listas, negritas, enlaces).
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  address?: T;
  city?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinaryURL?: T;
  cloudinaryPublicId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  category?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  sku?: T;
  inventory?: T;
  media?: T;
  specifications?:
    | T
    | {
        name?: T;
        value?: T;
        icon?: T;
        id?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  lines?:
    | T
    | {
        merchandiseId?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  user?: T;
  status?: T;
  customer?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        phone?: T;
        address?: T;
        city?: T;
      };
  lines?:
    | T
    | {
        productName?: T;
        quantity?: T;
        price?: T;
        merchandiseId?: T;
        id?: T;
      };
  totalPrice?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  showInFooter?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configura la apariencia, barra de progreso para envío gratis y mensajes informativos del Carrito de Compras.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-management".
 */
export interface StoreManagement {
  id: string;
  freeShipping?: {
    enabled?: boolean | null;
    /**
     * Monto que el cliente debe alcanzar en el subtotal de su carrito para obtener envío gratis (ej: 50, 100, 150).
     */
    thresholdAmount?: number | null;
  };
  footerMessages?: {
    enabled?: boolean | null;
    /**
     * Texto que acompaña el ícono de envío. Si no incluye un monto, se añadirá automáticamente el monto configurado arriba.
     */
    freeDeliveryText?: string | null;
    /**
     * Texto que acompaña el ícono de devolución.
     */
    returnsText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configura el nombre de tu tienda, logotipo, eslogan, descripción SEO y texto de copyright.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-identity".
 */
export interface StoreIdentity {
  id: string;
  /**
   * Nombre principal usado en el título de la pestaña del navegador y cabecera.
   */
  siteName: string;
  /**
   * Breve frase promocional o lema que se muestra en el pie de página.
   */
  tagline?: string | null;
  /**
   * Descripción por defecto para buscadores (Google) y redes sociales.
   */
  description?: string | null;
  /**
   * Nombre que aparece al final del pie de página después de © y el año actual.
   */
  copyrightHolder?: string | null;
  /**
   * Sube una imagen o SVG con fondo transparente (formato horizontal / apaisado). Tamaño recomendado: 180x40 px a 240x60 px (altura visual adaptada a 40px en cabecera).
   */
  logo?: (string | null) | Media;
  /**
   * Versión en color blanco o claro para fondos oscuros (Footer). Tamaño recomendado: 180x40 px a 240x60 px.
   */
  logoInverted?: (string | null) | Media;
  /**
   * Icono cuadrado para la pestaña del navegador en formato PNG, ICO o SVG. Tamaño recomendado: 32x32 px o 64x64 px.
   */
  favicon?: (string | null) | Media;
  announcement?: {
    enabled?: boolean | null;
    /**
     * Mensaje conciso que verán todos los usuarios al entrar a la tienda.
     */
    text?: string | null;
    /**
     * Ejemplo: /products o /category/relojes
     */
    linkUrl?: string | null;
    linkLabel?: string | null;
  };
  hero?: {
    enabled?: boolean | null;
    /**
     * Texto sutil en mayúsculas sobre el título principal.
     */
    badge?: string | null;
    /**
     * Título corto e impactante para tu tienda.
     */
    title?: string | null;
    description?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    /**
     * Imagen de fondo para el Hero Banner. Tamaño recomendado: 1920x600 px o relación de aspecto horizontal 16:5. Formatos recomendados: JPG o WebP de alta resolución.
     */
    backgroundImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Configura el número de WhatsApp comercial para pedidos, información de contacto de soporte y enlaces a redes sociales.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-contact".
 */
export interface StoreContact {
  id: string;
  enabled?: boolean | null;
  /**
   * Código de país seguido del número telefónico, sin símbolo + ni espacios (ejemplo: 584120000000, 5215500000000, 34600000000).
   */
  businessPhone: string;
  /**
   * Frase inicial del mensaje automático en WhatsApp.
   */
  defaultMessagePrefix?: string | null;
  supportEmail?: string | null;
  supportPhone?: string | null;
  address?: string | null;
  cityCountry?: string | null;
  hours?: string | null;
  showSocialLinks?: boolean | null;
  /**
   * Ejemplo: https://instagram.com/tumarca o @tumarca
   */
  instagram?: string | null;
  facebook?: string | null;
  twitter?: string | null;
  tiktok?: string | null;
  whatsappSupport?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-management_select".
 */
export interface StoreManagementSelect<T extends boolean = true> {
  freeShipping?:
    | T
    | {
        enabled?: T;
        thresholdAmount?: T;
      };
  footerMessages?:
    | T
    | {
        enabled?: T;
        freeDeliveryText?: T;
        returnsText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-identity_select".
 */
export interface StoreIdentitySelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  copyrightHolder?: T;
  logo?: T;
  logoInverted?: T;
  favicon?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        linkUrl?: T;
        linkLabel?: T;
      };
  hero?:
    | T
    | {
        enabled?: T;
        badge?: T;
        title?: T;
        description?: T;
        ctaText?: T;
        ctaLink?: T;
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "store-contact_select".
 */
export interface StoreContactSelect<T extends boolean = true> {
  enabled?: T;
  businessPhone?: T;
  defaultMessagePrefix?: T;
  supportEmail?: T;
  supportPhone?: T;
  address?: T;
  cityCountry?: T;
  hours?: T;
  showSocialLinks?: T;
  instagram?: T;
  facebook?: T;
  twitter?: T;
  tiktok?: T;
  whatsappSupport?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}